name: Test Helpers
on:
  workflow_run:
    workflows: ["Pull Request Tests"]
    types:
      - requested
env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  startrunner:
    name: Start ec2 instances
    runs-on: ubuntu-20.04

    steps:
    - name: Check out codes
      uses: actions/checkout@v2

    - name: Check job status
      run: |
        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.event.workflow_run.id }}/jobs
        echo "jobs_url is $jobs_url"
        echo $jobs_url | ./job_status_check.py "Build" 2>&1
        jobs_url2=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.event.workflow_run.id }}/jobs
        echo "jobs_url2 is $jobs_url2"

#  stoprunner:
#    name: Stop ec2 instances
#    runs-on: ubuntu-20.04
#
#    steps:
#    - name:
#      run:
