name: Test_Helpers
on:
  workflow_run:
    workflows: ["Pull Request Tests"]
    types:
      - requested
env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  startrunner:
    name: Start ec2 instances
    runs-on: ubuntu-20.04

    steps:
    - name: Check out codes
      uses: actions/checkout@v2

    - name: Check job status
      run: |
        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.event.workflow_run.id }}/jobs
        conclusion=$(echo $jobs_url | ./job_status_check.py "Build")
        echo "conlusion is $conclusion"

  stoprunner:
    name: Stop ec2 instances
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout out codes
      uses: actions/checkout@v2

    - name: Check job status
      run: |
        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.event.workflow_run.id }}
        echo $url | ./job_status_check.py
