name: Test Helpers
on:
  workflow_run:
    workflows: ["Pull Request Tests"]
    types:
      - requested
env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  startrunner:
    name: Start ec2 instances
    runs-on: ubuntu-20.04

    steps:
    - name: Check out codes
      uses: actions/checkout@v2

    - name: Check job status
      run: |
        jobs_url=${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/{$GITHUB_RUN_ID}/jobs
        echo "jobs_url is $jobs_url"
        echo https://api.github.com/repos/MinsukJi-NOAA/actions_control/actions/runs/749704180/jobs | ./job_status_check.py "Build" 2>&1

#  stoprunner:
#    name: Stop ec2 instances
#    runs-on: ubuntu-20.04
#
#    steps:
#    - name:
#      run:
